### ISSUE TITLE
Garbage noise and beeps

### ISSUE THREAD

**Issue by Aisflou** [jsanpe/SwinsidNeat#1]
Hell, i just order some pcbs to make a couple of this replacements as your design looks so much more neat :D all went well, i programmed the ics without problem. The first unit that i soldered went to a friend, with an ASSY NO. 250407 board, as the tittle says, he gets noises and beeps, not reasembling to any correct sound, his sid works mostly well, so, not a problem of the mainboard it seems, he tried changing the jumpers, with no luck, same noises... he used kungfuflash and rad to make the test, same results... do you think of something we can test maybe? Thanks anyway for the project as it looks so great indeed. Hope we can found the problem and be able to fix it! :D Greetings!

**Comment by jsanpe** [comment]
Hi there. Not sure what could be goin on to be honest. In my own testing I got good quality sound out of the board, so my guess is that something went wrong during the assembly of the board. Check the resistor values and connectivity, note that the output signal is composed by transforming PWM pulses into the audio wave through a network of resistors. If something is wrong in this network, the the output can be affected. Another part to check is the crystal, check that it is outputing the right frequency.

There's really nothing new to this design other that the aesthetics, it's the well tested Swinsid. My guess is that there's a faulty part or a bad connection going on.

**Comment by Aisflou** [comment]
Thanks, i will make another one and test it on my own c64 to see it ifs just the unit i sent to my friend, probably thats the problem :D

**Comment by Aisflou** [comment]
Hello, im happy to say that i am a total stupid, forgot to configure the fuses correctly, that was the issue :( sorry for bother and thanks for all! You can add that the desing functions well as expected. Greetings!
